export const DAILY_SPARK_BITS = [
    "Small steps beat big plans left undone.",
    "Consistency is louder than intensity.",
    "Start tiny, then protect the streak.",
    "Progress compounds when repeated daily.",
    "Done today is better than perfect someday.",
    "A two-minute start can unlock an hour of focus.",
    "One clear action beats ten vague intentions.",
    "A calm routine outlasts a burst of hype.",
    "Tiny wins train your brain to trust itself.",
    "Keep the bar low enough to begin every day.",
    "You can be tired and still be consistent.",
    "The first minute decides the next thirty.",
    "Daily effort is a vote for your future.",
    "Skip the drama, keep the rhythm.",
    "Today is where momentum is minted.",
    "Simple plans are easier to repeat.",
    "Build the habit before you build speed.",
    "Small reps turn into strong identity.",
    "Treat start time like an appointment.",
    "Clarity grows after action, not before.",
    "A short session still counts as progress.",
    "What you repeat, you become.",
    "Less friction, more follow-through.",
    "A reliable routine beats a perfect one.",
    "Do the next obvious step.",
    "Progress loves a calendar and a checkbox.",
    "Protect your chain one day at a time.",
    "Motivation fades, structure remains.",
    "Good days build confidence, hard days build character.",
    "Finish the day proud of one promise kept.",
];

export const HABIT_WISDOM = [
    "Design your environment before relying on willpower.",
    "Pair a new habit with one you already do.",
    "Track what matters, not what looks impressive.",
    "Miss once, recover immediately.",
    "Make the good habit easy and the bad habit harder.",
    "Identity follows repeated action.",
    "Your defaults are stronger than your decisions.",
    "Put cues where your eyes already go.",
    "Reduce choice when discipline feels low.",
    "Use time and place, not mood, as your trigger.",
    "Habit strength comes from repetition, not emotion.",
    "Build for average days, not ideal days.",
    "If it is hard to start, shrink the first step.",
    "Create a stop signal for bad habits.",
    "Reward completion immediately, even if briefly.",
    "A visible streak can steady a shaky day.",
    "Do not negotiate with your plan every morning.",
    "Automate the setup so action feels obvious.",
    "When in doubt, do the minimum viable version.",
    "Replace a bad loop with a better loop.",
    "The easiest behavior usually wins.",
    "Name the cue, routine, and reward.",
    "Choose habits that fit your real life.",
    "Consistency needs recovery, not perfection.",
    "Guard your triggers like valuable assets.",
    "Set rules once, follow them many times.",
    "A prepared environment saves future effort.",
    "Stack new habits onto stable anchors.",
    "Treat friction like a design bug.",
    "Practice restarting as a core skill.",
];

export const MOTIVATION_SPARKS = [
    "Future you is built by today you.",
    "Momentum starts with one honest rep.",
    "You do not need motivation to begin, only a first action.",
    "Show up before you feel ready.",
    "Action creates clarity.",
    "Keep promises to yourself, especially small ones.",
    "Start where you are, with what you have.",
    "Discipline is self-respect in motion.",
    "Courage often looks like starting small.",
    "Do it for the person you are becoming.",
    "Your goals need your calendar, not your mood.",
    "The next right action is enough for now.",
    "You are one decision away from momentum.",
    "Effort today lowers resistance tomorrow.",
    "Progress is a pattern, not a miracle.",
    "Keep the promise, keep the confidence.",
    "You can start over without starting from zero.",
    "One focused block can change your whole day.",
    "Your standard rises when your follow-through rises.",
    "Hard now, easier later.",
    "A strong day begins with one completed task.",
    "Trust is built by doing what you said.",
    "Small courage repeated becomes resilience.",
    "Begin first, optimize later.",
    "Move forward before you feel certain.",
    "The streak starts at one.",
    "Show up and let momentum do the rest.",
    "A little progress still moves your life.",
    "You are not behind when you restart today.",
    "Your next step matters more than your last miss.",
];

export const GROWTH_NUGGETS = [
    "Measure trendlines, not single days.",
    "A setback is data, not failure.",
    "Raise the floor before raising the ceiling.",
    "Protect your routines on hard days.",
    "Your systems decide your outcomes.",
    "Discomfort is often the price of change.",
    "Feedback is fuel when ego is quiet.",
    "Refine one variable at a time.",
    "Keep what works, drop what drains.",
    "Compounding favors patience and repetition.",
    "Growth is rarely loud, usually steady.",
    "Do not confuse busy with effective.",
    "Iteration beats hesitation.",
    "Adjust the plan, not the mission.",
    "Your baseline matters more than your peak.",
    "What gets measured gets managed.",
    "One correction today prevents ten tomorrow.",
    "The process is the product.",
    "Consistency turns effort into skill.",
    "Plateaus are often preparation, not failure.",
    "Keep the main thing the main thing.",
    "Train reliability before intensity.",
    "Sustainable beats spectacular.",
    "Do fewer things, better and longer.",
    "Clarity arrives through repetition.",
    "Long-term change is built on boring excellence.",
    "Protect your energy like a finite budget.",
    "Improve the setup and results will follow.",
    "Wins become habits when documented.",
    "Growth begins where excuses end.",
];

export const TINY_HABIT_INSIGHTS = [
    "Shrink the task until it feels impossible to skip.",
    "Anchor habits to a specific cue and time.",
    "Celebrate completion to reinforce the loop.",
    "Lower friction for starting by one step.",
    "Decide the minimum version in advance.",
    "Repetition wires confidence.",
    "Put tools in reach before you need them.",
    "Start with one minute and protect it.",
    "Choose obvious cues over clever ones.",
    "Link effort to a concrete next action.",
    "Default to tiny when energy is low.",
    "Attach habits to existing routines.",
    "Keep a backup version for chaotic days.",
    "Make your first step visible and simple.",
    "Use the same trigger until it feels automatic.",
    "Tiny starts reduce procrastination.",
    "Consistency loves predictable cues.",
    "Never let setup be harder than execution.",
    "The easiest version keeps the chain alive.",
    "Cut startup time to under one minute.",
    "A habit is easier when the path is pre-decided.",
    "Store reminders where action happens.",
    "Use environment as your silent coach.",
    "Lower standards for starting, not for showing up.",
    "A tiny action still reinforces identity.",
    "Choose repeatable over ambitious.",
    "Keep your fallback small and non-negotiable.",
    "Consistency is often a setup problem.",
    "Make good choices the default choice.",
    "Small routines scale better than heroic efforts.",
];

export const MOMENTUM_TIPS = [
    "Finish today by setting up tomorrow.",
    "Use streaks to stay engaged, not to punish slips.",
    "Batch decisions so execution stays simple.",
    "Keep your next action visible.",
    "Protect your first productive hour.",
    "Win the day early with one meaningful task.",
    "Prepare your tools before the work block starts.",
    "Start with a quick win to build traction.",
    "Do hard tasks before decision fatigue hits.",
    "Create rituals that trigger focus quickly.",
    "Use short deadlines to prevent drift.",
    "Keep your momentum list short and clear.",
    "Reset fast after interruptions.",
    "Carry forward only what still matters.",
    "Leave clues for your future self.",
    "Track starts, not just finishes.",
    "Protect progress with simple boundaries.",
    "Use momentum to enter the next task, not a break spiral.",
    "When stalled, reduce scope and continue.",
    "Schedule recovery so momentum remains sustainable.",
    "Build cadence first, then volume.",
    "Stack small wins in the same direction.",
    "Guard your attention from low-value noise.",
    "Keep friction low between one task and the next.",
    "When energy dips, execute the smallest useful step.",
    "A clean workspace can restart momentum quickly.",
    "Use checklists to protect consistency under stress.",
    "Treat every restart as a win signal.",
    "Protect your evenings from next-day sabotage.",
    "Move the ball daily, even by inches.",
];

export const DAILY_SPARK_LIBRARY = [
    ...DAILY_SPARK_BITS,
    ...HABIT_WISDOM,
    ...MOTIVATION_SPARKS,
    ...GROWTH_NUGGETS,
    ...TINY_HABIT_INSIGHTS,
    ...MOMENTUM_TIPS,
];
