import {
    Dumbbell, BookOpen, Coffee, Brain, Heart, Bike, Droplets, Apple,
    Moon, Sun, Music, Pencil, Phone, Laptop, Leaf, Flame, Star, Shield,
    Zap, Target, Timer, Footprints, BedDouble, Wind, Salad, Pill,
    Smile, Camera, Palette, Scissors, Dog, Fish, Flower, TreePine,
    Glasses, Headphones, Watch, Wallet, Car, Plane, Home, Bell,
    GraduationCap, ChefHat, Brush, CupSoda, Beer,
    Cigarette, Globe, Handshake, Lightbulb, Lock, Mic, Search, Settings,
    Swords, Trophy, Umbrella, Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const HABIT_ICONS: Record<string, LucideIcon> = {
    Dumbbell,
    BookOpen,
    Coffee,
    Brain,
    Heart,
    Bike,
    Droplets,
    Apple,
    Moon,
    Sun,
    Music,
    Pencil,
    Phone,
    Laptop,
    Leaf,
    Flame,
    Star,
    Shield,
    Zap,
    Target,
    Timer,
    Footprints,
    BedDouble,
    Wind,
    Salad,
    Pill,
    Smile,
    Camera,
    Palette,
    Scissors,
    Dog,
    Fish,
    Flower,
    TreePine,
    Glasses,
    Headphones,
    Watch,
    Wallet,
    Car,
    Plane,
    Home,
    Bell,
    GraduationCap,
    ChefHat,
    Brush,
    CupSoda,
    Beer,
    Cigarette,
    Globe,
    Handshake,
    Lightbulb,
    Lock,
    Mic,
    Search,
    Settings,
    Swords,
    Trophy,
    Umbrella,
    Wrench,
};
